Add pagination to homepage
htdvisser/hugo-base16-theme pull request #17
Opened 2018-06-23 19:21 UTC by keanemind

Adds feature requested in #2. Quite a dirty way of doing it, there might be a better way.

2018-06-25 07:05 UTC, htdvisser requested changes
Thanks for your contribution. The template part looks okay to me, I will try it out later. Let's move the styles out of the HTML and into the CSS file.

2018-09-18 14:24 UTC, denislobanov reviewed
I was just going to implement the very same thing when I realised that you have already done all the hard work and even added a PR. So I hope you dont mind if I add some feedback? :)

2018-09-18 14:24 UTC, denislobanov commented on layouts/partials/homepage.html
> +    {{ range (.Paginate (where .Data.Pages "Section" "post") 3).Pages }}
It would be nice to use the default Paginator page size config, since then I could configure how many posts I have per page. I have just been looking at implementing this change before I realised you have a PR, this was my approach:

```
{{ $paginator := .Paginate (where .Data.Pages "Section" "post") }}
{{ range $paginator.Pages }}
```

This does mean that your logic further down is going to have to use the local $paginator var instead..

2018-09-18 14:24 UTC, denislobanov commented on layouts/partials/homepage.html
> +  {{ if or (.Paginator.HasPrev) (.Paginator.HasNext) }}
You could also do something like 
```
{{ if gt .Paginator.TotalPages 1 }}
```

Not that either approach is wrong, but maybe this show intention a little more clearly than two `HasNext` `HasPrev` checks :p

2018-09-18 14:24 UTC, denislobanov commented on layouts/partials/homepage.html
> +    <span>{{ .Paginator.PageNumber}} / {{ .Paginator.TotalPages }}</span>
I like this! Much nicer than a long list of page numbers :D

2018-09-18 14:25 UTC, denislobanov commented on layouts/partials/homepage.html
> +    {{ range (.Paginate (where .Data.Pages "Section" "post") 3).Pages }}
This allows me to put `paginate = 5` or whatever into my `config.toml` and I can control how many posts per page I see on my blog :)

2018-09-25 16:00 UTC, htdvisser commented on layouts/partials/homepage.html
> +    {{ range (.Paginate (where .Data.Pages "Section" "post") 3).Pages }}
I guess we can just remove the `3` argument from @keanemind's diff, right? The only problem then is that the default value is 10, so we'd need to override that somewhere if possible.

2018-09-26 10:40 UTC, denislobanov commented on layouts/partials/homepage.html
> +    {{ range (.Paginate (where .Data.Pages "Section" "post") 3).Pages }}
> I guess we can just remove the 3 argument from @keanemind's diff, right? 
Yes

> we'd need to override that somewhere if possible.
Easily done by setting the `paginate` config variable to something other than 10. I'm not sure but [I think themes can provide default configs](https://gohugo.io/themes/creating/#theme-configuration-file) so `paginate` can always be set to 3 there, this has the nice advantage of allowing a user to change it in *their* config and display more posts on their blog should they wish.

2019-03-29 13:09 UTC, denislobanov commented
This PR has been open for a long time without changes... I hope you dont mind but I ended up implementing review feedback myself here: https://github.com/htdvisser/hugo-base16-theme/pull/18

2019-03-29 20:52 UTC, keanemind commented
I don't mind. I haven't had time to look back at this. I'm closing this PR in favor of @denislobanov's #18 .

2019-03-29 20:52 UTC, closed without merging